/*
 * This source file was generated by the Gradle 'init' task
 */
package com.darshil.demo;

public class App {
    public String getGreeting() {
        return "Hello World from gradle";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
